### ISSUE TITLE
Discussion on adaptive_avg_pool2d

### ISSUE THREAD

**Issue by zzhanghub** [mightyzau/InfMLLM#2]
Very inspiring work!
Why not use `torch.nn.functional.adaptive_avg_pool2d`? I see that you comment out [L38-42](https://github.com/mightyzau/InfMLLM/blob/0076c91cdb1724fd89c25f09361e437ba5208ee4/infmllm/models/pooler.py#L38); May I ask if there are any potential risk?

**Comment by mightyzau** [comment]
Thank you for your attention. Our early experiments showed that when $s$ is not divisible by $pool_out_size$, the final performance of the $adaptive_avg_pool2d$ scheme does not meet our expectations. We will add more comparative experiments in the revised manuscript.
